config/routes.rb
Mozbii::Application.routes.draw do
  devise_for :users, controllers: { sessions: "sessions", passwords: "passwords", registrations: "registrations" }
  devise_scope :user do
    post "password", to: "sessions#password"
    put "password", to: "passwords#update"
  end

  namespace :api, :defaults => { :format => 'json' } do
   resources :users do
    collection do
      post :forgot_password
      post :work_create
    end
   end
   resources :tokens, :only => [:create, :destroy]
  end

  resources :index, :ufro

  root "index#index"
end

app/controllers/ufro_controller.rb
class UfroController < ApplicationController
  before_action :set_page
  layout false, :only => [:show]

  def index
    @works = current_user.works.order('created_at desc')
  end

  def show
    @work = current_user.works.find(params[:id])
  end

  private

  def set_page
    @page = "ufro"
  end
end

app/views/ufro/index.html.haml
.container
  .row
    #content.col-lg-12{style: "min-height:801px !important"}
      / PAGE HEADER
      .row
        .col-sm-12
          .page-header
            / STYLER
            / /STYLER
            / BREADCRUMBS
            %ul.breadcrumb
              %li
                %i.fa.fa-home
                %a{href: "index.html"} Home
              %li Ufro
            / /BREADCRUMBS
            .clearfix
              %h3.content-title.pull-left Ufro
            .description Portfolio Gallery
      / /PAGE HEADER
      / GALLERY
      .row
        .col-md-12
          / BOX
          .box
            .box-title
              %h4
                %i.fa.fa-bars>
                Portfolio
              .tools
                %a.config{"data-toggle" => "modal", href: "#box-config"}
                  %i.fa.fa-cog
                %a.reload{href: "javascript:;"}
                  %i.fa.fa-refresh
                %a.collapse{href: "javascript:;"}
                  %i.fa.fa-chevron-up
                %a.remove{href: "javascript:;"}
                  %i.fa.fa-times
            .box-body.clearfix
              #filter-items.row.isotope{style: "position: relative; overflow: hidden; height: 434px;"}
                - @works.each_with_index do |w, i|
                  .col-md-3.category_1.item.isotope-item{style: "position: absolute; left: 0px; top: 0px; -webkit-transform: translate3d(0px, 0px, 0px);"}
                    .filter-content
                      %img.img-responsive{alt: "", src: "#{w.data}"}
                      .hover-content.animated.fadeOut{style: "display: block;"}
                        %h4 #{w.name}
                        %a.btn.btn-warning.hover-link.colorbox-button.cboxElement{href: "#{ufro_path(w)}", title: "Image Title"}
                          %i.fa.fa-search-plus.fa-1x
          / /BOX
      / /GALLERY
      .footer-tools
        %span.go-top
          %i.fa.fa-chevron-up
          Top
    / /CONTENT

app/views/ufro/show.html.haml
!!!5
%html
  %head
    = javascript_include_tag "http://w.sharethis.com/button/buttons.js"
    :javascript
      stLight.options({publisher: "ff07198f-f4d2-42ec-820b-48da31c13e96", doNotHash: false, doNotCopy: false, hashAddressBar: false});
  %body
    %img.img-responsive{alt: "", src: "#{@work.data}"}
    %br
    %div{:style => 'text-align: center'}
      %span.st_facebook_large{displaytext: "Facebook"}
      %span.st_twitter_large{displaytext: "Tweet"}
      %span.st_googleplus_large{displaytext: "Google +"}